manifest:
  version: 1.2
  defaults:
    revision: main
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: z8933e46761596791657c0e66c6d05f33663a8a0c
      import: app/west.yml
  self:
    path: config
